-- Google Home Professional Assessment - database schema
-- Apply with: supabase db push

create extension if not exists pgcrypto;

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  concept_key text not null,
  domain text not null check (domain in (
    'products','network','appliances','setup','security','automation','troubleshooting'
  )),
  difficulty text not null check (difficulty in ('medium','hard','very_hard')),
  question_type text not null check (question_type in ('single','multiple','scenario')),
  question_text text not null,
  explanation text not null default '', 
  max_points numeric(5,2) not null default 1 check (max_points > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists questions_selection_idx
  on public.questions (is_active, concept_key, domain, difficulty);

create table if not exists public.question_options (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  option_text text not null,
  is_correct boolean not null default false,
  sort_order smallint not null default 0,
  unique(question_id, sort_order)
);

create index if not exists question_options_question_idx
  on public.question_options(question_id);

create table if not exists public.exam_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  started_at timestamptz not null default now(),
  expires_at timestamptz not null,
  submitted_at timestamptz,
  status text not null default 'active' check (status in ('active','submitted','expired','cancelled')),
  score numeric(8,2),
  max_score numeric(8,2),
  percentage numeric(6,2),
  passed boolean,
  section_scores jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists one_active_attempt_per_user
  on public.exam_attempts(user_id)
  where status = 'active';

create index if not exists attempts_user_history_idx
  on public.exam_attempts(user_id, started_at desc);

create table if not exists public.attempt_questions (
  attempt_id uuid not null references public.exam_attempts(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  display_order smallint not null,
  option_order bigint[] not null,
  primary key (attempt_id, question_id),
  unique (attempt_id, display_order)
);

create table if not exists public.user_answers (
  attempt_id uuid not null references public.exam_attempts(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  selected_option_ids bigint[] not null default '{}',
  answered_at timestamptz not null default now(),
  primary key (attempt_id, question_id)
);

create table if not exists public.attempt_events (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.exam_attempts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('tab_hidden','tab_visible','window_blur','window_focus','network_offline','network_online')),
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists attempt_events_attempt_idx
  on public.attempt_events(attempt_id, created_at);

-- RLS: the browser may see only its own attempt metadata and answers.
-- Question text and answer keys are returned only by authenticated Edge Functions.
alter table public.questions enable row level security;
alter table public.question_options enable row level security;
alter table public.exam_attempts enable row level security;
alter table public.attempt_questions enable row level security;
alter table public.user_answers enable row level security;
alter table public.attempt_events enable row level security;

revoke all on public.questions from anon, authenticated;
revoke all on public.question_options from anon, authenticated;
revoke all on public.attempt_questions from anon, authenticated;
revoke all on public.attempt_events from anon, authenticated;

grant select on public.exam_attempts to authenticated;
grant select on public.user_answers to authenticated;

create policy "users_read_own_attempts"
  on public.exam_attempts for select
  to authenticated
  using (auth.uid() = user_id);

create policy "users_read_own_answers"
  on public.user_answers for select
  to authenticated
  using (
    exists (
      select 1 from public.exam_attempts a
      where a.id = user_answers.attempt_id
        and a.user_id = auth.uid()
    )
  );

-- No direct INSERT/UPDATE/DELETE policies are intentionally created.
-- All exam writes go through server-side Edge Functions using the service role.
